name: CI/CD FastAPI Docker Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Cloner le code
      uses: actions/checkout@v4

    - name: Installer Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Construire l'image Docker
      run: docker build -t cryptoimage:latest .

    - name: Lancer le conteneur
      run: docker run -d -p 8000:8000 --name crypto_test cryptoimage:latest

    - name: Vérifier que l’API répond
      run: |
        sleep 5
        curl -f http://localhost:8000/docs || (echo "API non accessible" && exit 1)

    - name: Nettoyer le conteneur
      run: docker rm -f crypto_test
