name: Simple CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Compiler le programme
        run: |
          echo "Compilation du projet..."
          g++ main.cpp hello.cpp -o monprog

      - name: Exécuter le programme
        run: |
          echo "Lancement du programme..."
          ./monprog
