name: CI/CD FastAPI Multi-Jobs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job 1 : Build de l'image Docker
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cloner le code
        uses: actions/checkout@v4

      - name: Installer Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Construire l'image Docker
        run: docker build -t cryptoimage:latest .

      - name: Vérifier la présence de l'image
        run: docker images | grep cryptoimage

  # Job 2 : Test de l'API dans un conteneur
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Cloner le code
        uses: actions/checkout@v4

      - name: Installer Docker
        uses: docker/setup-buildx-action@v3

      - name: Lancer le conteneur
        run: docker run -d -p 8000:8000 --name crypto_test cryptoimage:latest

      - name: Vérifier que l’API répond
        run: |
          sleep 5
          curl -f http://localhost:8000/docs || (echo "API non accessible" && exit 1)

  # Job 3 : Nettoyage du conteneur et des images
  cleanup:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Supprimer les conteneurs et images Docker
        run: |
          docker rm -f $(docker ps -aq) || true
          docker rmi -f cryptoimage:latest || true
